#!/nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor 'HDMI-0' -d 'I' 'II' 'III' 'IV' 'V'

bspc config 'border_width' '2'
bspc config 'borderless_monocle' 'on'
bspc config 'gapless_monocle' 'on'
bspc config 'pointer_action1' 'move'
bspc config 'pointer_action2' 'resize_side,resize_corner'
bspc config 'pointer_modifier' 'mod4'
bspc config 'split_ratio' '0.520000'
bspc config 'window_gap' '12'

bspc rule -r '*'
bspc rule -a 'firefox' 'border=off' 'state=floating'
bspc rule -a 'steam' 'border=off' 'state=floating'

# java gui fixes
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a sun-awt-X11-XDialogPeer state=floating

~/.fehbg &
polybar &
feh &

